services:
  kagzi-db:
    image: postgres:alpine
    command: postgres -c 'max_connections=1000'
    restart: always
    hostname: "kagzi-db"
    ports:
      - 54122:5432
    volumes:
      - kagzi_postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

volumes:
  kagzi_postgres_data:
