[package]
name = "kagzi-server"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "kagzi-server"
path = "src/main.rs"

[dependencies]
kagzi-proto = { path = "../kagzi-proto" }
tonic.workspace = true
tonic-reflection.workspace = true
prost.workspace = true
tokio.workspace = true
sqlx.workspace = true
uuid.workspace = true
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
prost-types = "0.14.1"
